
services:
  # ====================== Config Servers (3 ноды) ======================
  cfg1:
    image: mongo:7
    container_name: cfg1
    command: mongod --configsvr --replSet cfgrs --bind_ip_all --port 27019
    ports:
      - "27019:27019"
    volumes:
      - cfg1-data:/data/db
    networks:
      - mongodb-network

  cfg2:
    image: mongo:7
    container_name: cfg2
    command: mongod --configsvr --replSet cfgrs --bind_ip_all --port 27019
    ports:
      - "27020:27019"
    volumes:
      - cfg2-data:/data/db
    networks:
      - mongodb-network

  cfg3:
    image: mongo:7
    container_name: cfg3
    command: mongod --configsvr --replSet cfgrs --bind_ip_all --port 27019
    ports:
      - "27021:27019"
    volumes:
      - cfg3-data:/data/db
    networks:
      - mongodb-network

  # ====================== Шард 1 (Replica Set из 3 нод) ======================
  shard1-rs1:
    image: mongo:7
    container_name: shard1-rs1
    command: mongod --shardsvr --replSet shard1rs --bind_ip_all --port 27018
    ports:
      - "27018:27018"
    volumes:
      - shard1-rs1-data:/data/db
    networks:
      - mongodb-network

  shard1-rs2:
    image: mongo:7
    container_name: shard1-rs2
    command: mongod --shardsvr --replSet shard1rs --bind_ip_all --port 27018
    ports:
      - "27028:27018"
    volumes:
      - shard1-rs2-data:/data/db
    networks:
      - mongodb-network

  shard1-rs3:
    image: mongo:7
    container_name: shard1-rs3
    command: mongod --shardsvr --replSet shard1rs --bind_ip_all --port 27018
    ports:
      - "27038:27018"
    volumes:
      - shard1-rs3-data:/data/db
    networks:
      - mongodb-network

  # ====================== Шард 2 (Replica Set из 3 нод) ======================
  shard2-rs1:
    image: mongo:7
    container_name: shard2-rs1
    command: mongod --shardsvr --replSet shard2rs --bind_ip_all --port 27018
    ports:
      - "27048:27018"
    volumes:
      - shard2-rs1-data:/data/db
    networks:
      - mongodb-network

  shard2-rs2:
    image: mongo:7
    container_name: shard2-rs2
    command: mongod --shardsvr --replSet shard2rs --bind_ip_all --port 27018
    ports:
      - "27058:27018"
    volumes:
      - shard2-rs2-data:/data/db
    networks:
      - mongodb-network

  shard2-rs3:
    image: mongo:7
    container_name: shard2-rs3
    command: mongod --shardsvr --replSet shard2rs --bind_ip_all --port 27018
    ports:
      - "27068:27018"
    volumes:
      - shard2-rs3-data:/data/db
    networks:
      - mongodb-network

  # ====================== Шард 3 (Replica Set из 3 нод) ======================
  shard3-rs1:
    image: mongo:7
    container_name: shard3-rs1
    command: mongod --shardsvr --replSet shard3rs --bind_ip_all --port 27018
    ports:
      - "27078:27018"
    volumes:
      - shard3-rs1-data:/data/db
    networks:
      - mongodb-network

  shard3-rs2:
    image: mongo:7
    container_name: shard3-rs2
    command: mongod --shardsvr --replSet shard3rs --bind_ip_all --port 27018
    ports:
      - "27088:27018"
    volumes:
      - shard3-rs2-data:/data/db
    networks:
      - mongodb-network

  shard3-rs3:
    image: mongo:7
    container_name: shard3-rs3
    command: mongod --shardsvr --replSet shard3rs --bind_ip_all --port 27018
    ports:
      - "27098:27018"
    volumes:
      - shard3-rs3-data:/data/db
    networks:
      - mongodb-network

  # ====================== Mongos Router ======================
  mongos:
    image: mongo:7
    container_name: mongos
    command: mongos --configdb cfgrs/cfg1:27019,cfg2:27019,cfg3:27019 --bind_ip_all --port 27017
    ports:
      - "27017:27017"  # Основной порт для подключения клиентов
    depends_on:
      - cfg1
      - cfg2
      - cfg3
      - shard1-rs1
      - shard2-rs1
      - shard3-rs1
    networks:
      - mongodb-network

# ====================== Настройки сети и томов ======================
networks:
  mongodb-network:
    driver: bridge

volumes:
  cfg1-data:
  cfg2-data:
  cfg3-data:
  shard1-rs1-data:
  shard1-rs2-data:
  shard1-rs3-data:
  shard2-rs1-data:
  shard2-rs2-data:
  shard2-rs3-data:
  shard3-rs1-data:
  shard3-rs2-data:
  shard3-rs3-data: